version: '3.8'
services:
  apache-php:
   build:
    context: .
    dockerfile: dockerfile-php-apache
   networks:
    - backend
   volumes:
    - ./db-data/:/var/www/html/
   ports:
    - 80:80
   depends_on:
    - mysql
  mysql:
   build:
    context: .
    dockerfile: dockerfile-bdd
   networks:
    - backend
networks:
  backend:
